apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-dns-secret
stringData:
  api-token: ENC[AES256_GCM,data:wdZ0PGaS/8RB8OK4JIGdF5XMbSLmOwWyhENuoZLD1y9K4tOQODZCsA==,iv:QC9XcD/jPCxnRhjHISwF8W8YdJqysj+Wj3tPkBu00EM=,tag:fk5f7pi5D0H5Fv8gfq7J3A==,type:str]
sops:
  age:
    - recipient: age15krcjh9hpde6hxwrkwlkpksf0kxhjygryn52xahqkllj6d9724lsm0m33a
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBHdG9TQkRUQzluK3F3WnJs
        bWFDaVhiR2VETkFpQnpKd0U2NUYybEp5UlY0CmxOVVYvU1FwRENHcnZvNXQyRFdM
        ZDQwdW9qTjhQaTJsMFU2QjdoYmZzR2cKLS0tIHNwR3UvRmg2VDBEaUpveWlVTU9h
        MUszcTZseVF3ckt1Q3crc2pWaEJYazAKkUkbb6cUewwCaOL18oO21FD2Sy6t7BxN
        DRVi3dW2epttB+qJLcauwwdWKDCg+I2HwNNdDb+5x+3zp6E8Vm9JUA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-02-15T06:22:14Z"
  mac: ENC[AES256_GCM,data:QYpAhqf23zNeC5iUpJQjyP5Kq298ndE8U5tmaJd+PWbNDaQLXjzfdt35DNmb0M0rbgP5B7DC/IcOxtxyipJ2YgqzqJg2X1rAgZTtamG6HTCcNrOJz8TFTNivYRYPtHf/+dKKMDIEnODIEI81UUXJOVu8m61Cal6TD/vm3oyxwlI=,iv:80/M9tgo9g0o6eZG5ivKkePmoXbSjvNKERCSAHXygu4=,tag:e6WAu+O2SnTHRX5CW8EF8g==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
