apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-dns-secret
stringData:
  api-token: ENC[AES256_GCM,data:vToi3o3ltrYQRJnoEhCaP8895tSLESwhfhGs1/4lDFwKOKD6P9wIrA==,iv:WFNeC7Xok+rS1pF4PyHGeNtbWcyi9Qk5oXGgk00VXqw=,tag:BYnlm9M1XsH/nWWlBPp0hg==,type:str]
sops:
  age:
    - recipient: age1vec5q7tvefy794m00e59hfa7xj3twg9d8ecsk4khj36cduhfauasl45avn
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBNVzhNa0lTMnhBZmdOZUJh
        dE1BQXVPV2p1MXdRdlFJK3YwK0ZRTi9QZ1ZvClZBeGtlY0VKSjVMT290NzRDRHgx
        Ty9HWE9XeDZ2bk82ZEZBbjF4dWtVakkKLS0tIFovRWY5ZVBmN1R1aHlUNG02dTVs
        aThlaEdqR09OUVE5UDNzV3ZEeEhkeE0KD46eLvdwt2R+ofqtItBj/88Bxjd295rr
        kOKRjvbDtdtSgM/n7xJ/LZ6xjqv08Q1iJaTZimsNF2JUDTappV6/Ew==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-02-14T13:52:34Z"
  mac: ENC[AES256_GCM,data:S2JOuQ6xGYKg8kBfV0y9vGpuocwZo2xVx7V0DTEpJN01dv/ppI3NuUnXBvkMYvljnQ8lJjZng/a/eNkPcBbwRW9MJB4sTJ3ky3MRRKwGNbS0keBsXdRCApcpnGSpFJV+9xrSExEjvtImc8G5TKZNmqs7TES9bNaeb5TSLnekqlc=,iv:v4xjDOUrJPPsTbCDaKAz95c5406s5mjBbTA1PkpP43o=,tag:DReegnCccb4bQEEWkIrKwg==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
