apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-dns-secret
stringData:
  api-token: ENC[AES256_GCM,data:uaqqjYiJsXgAL5XAo+R3PDhU+4hgFHJX+LoeHrx5sa9yHd73iv0qAA==,iv:Y3jq/X5JuK8hPjZp0vytahjUI5p8l1y3ZdmEILNKwGM=,tag:mSZTsiKY2JH3xJ1DS+pvjA==,type:str]
sops:
  age:
    - recipient: age1zrsvwesl8thdppjq78dq5qyntpc959twe97mplqg393vwpvg0gpsd6wy4r
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBqM2NVNmVQYWVnNzZGcmtT
        UVNVMEhDZERMeXFzZG54L2NxT1lhNFBleVFjCkhPL0FHSTBEVS8yNXhrczBkTHN2
        ekNMVitiK3JKZnIrc0NRcDRmL1F0OUUKLS0tIHpmY0x0cSt1UitKbGliTE43dWx4
        ZTB0Mk5zZklwbmM1eXB5ajB3Sk9WT1UKRwGItVlnkjXKW9egTNTQAagHepLdgDIp
        k5fWGR9rjkbwEhY0o92VBdQxY28DiRz75cwB5x/3EZu5z0D2eZy9KA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-02-14T02:21:45Z"
  mac: ENC[AES256_GCM,data:DmaO5jiO5KXCzXLMOu/M07/f2C9/FeIJoKqxbutKKYQnLSHXwhzuUn5hl8eehTAek3cYvCu6RWyK6RvKJ6NwC2dM9hgoC1REW8j/PBSQ39Dp357u1xBMZAM732dzD2iYJp+qSzcRG3cucIlr3kEX3E+PMdInTONUMI39ZZrl6Hg=,iv:PGf+2fXwNxI7onwv5wSJsjRMnl1fYrF4DQcHJjv+z6k=,tag:5G+QagzBWvONycKJjHnI3Q==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
