apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-dns-secret
stringData:
  api-token: ENC[AES256_GCM,data:J7KWjNMFyjnxP9r6PrfuDWdj2mUB8xH+zY3Tbm2ORUszx4UPSNpHgw==,iv:F0xnkhHUXXFQ9G1nNNdhqPfD2iw26KzPQKhC5a2Oeew=,tag:ZhlWxRMG/XEaydoklH80GQ==,type:str]
sops:
  age:
    - recipient: age14xzugqgv3lkrgvjpppls5vzn7j2vkrgxzghhkku7vpzf9cxjc3msdf4nha
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBiNGZydnRFZTZYeVRyNjhH
        dW9IbWFTNlZ0a3lEdjdGdXpsWUdNN3BGNlR3CjczaHFjYkkwemErY2NSSTV6MEhG
        cjdlR0ZiUzZnRHJsNGRZaE01RWk1UjQKLS0tIFNpWlNjcUpETWx0ZHhzWFdSd3g4
        cEpZVjNvWHZPN0RrTlkyYXhJa0Z6OFkKiNyHL7Vda1YkPZYelBqFUm3taeUBGOuZ
        0g0f+Y2CYaf8qXZnEVAPoPVQkgwWNVxO9MzDyqd3ltEXI4nv+JBs3g==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-02-08T13:55:02Z"
  mac: ENC[AES256_GCM,data:KYUy02fwNOP/avc+vfQ6QGwpkm2jXgI2qGhopGGS8zC2p0IwEr7Jrx3fjHFe30Err/H5AnbL+uhJpDegep08vkVllDkzeoIYksGtFsfzTXTzBX063rAiudJqn+JpNIPDJO0XYa0SLJxeEzNTAadPXRntu7PLA2GYT9ORTbWMggs=,iv:XGoUfUEXfsBl8G3rZ23CXJUogCEfhP55qIglV9U7mFI=,tag:fELk0FSxMLKleM+uX8jbAg==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
