apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-dns-secret
stringData:
  api-token: ENC[AES256_GCM,data:7+5+W/4sCJ/1TWpsFE+wc9b0CeTI13DbmEtYDszI6y7yF3hgvLpK/Q==,iv:0W8Z2PrqSHwMKPiRu6UAFHCK9apFjEQGwvZJ/yw+9I4=,tag:X1GIfNvFh0uNfRbsD9jtIQ==,type:str]
sops:
  age:
    - recipient: age14xzugqgv3lkrgvjpppls5vzn7j2vkrgxzghhkku7vpzf9cxjc3msdf4nha
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBHL1VpM2dLRlVGK3FtbkM4
        ZFFYMWZZRFA4RUpXNGIrbE9rWUlSczR4b1hvCk41OVhOa1pmWjl0ZVM0UHBGbHJr
        OEtsd0VNSGFOc2grZzlMR0YyY0syeEEKLS0tIHZJTHZTNmJuRUdIM09yeGdTK2dQ
        MmpwcnBlektjMUQxdmdDaU4yb3l4SnMKRtwLWySvWPnsO2t1JRl/AKrbaeH6YqSN
        ZB7eoGXpdGMjq6x9RnVZ878t3bj2l2NHly2pokcishta9IdgkQL7ng==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-02-14T00:53:39Z"
  mac: ENC[AES256_GCM,data:sMFbGu1O0AB+VUJWYNn1YIHrCim4vRPOfAbyZZXfIDJ8wV5cnLjv/lRmfCbrLtQl/JUZidErmiSSOxDtAPkezA2PzXy0Bw8mlnxwUCOI2NEsx8xg2bUXvcacp6r9csTXjaOCViq4OMoWdvf/xMXb263UlNc9Z5yyko4WiUbT6jw=,iv:dQzEM6PWe9KDFkaPmSqMYm4zTr6F84q2UUfkKN43P0w=,tag:vtALTNW5U1F7qJclUgneTA==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
