apiVersion: v1
kind: Secret
metadata:
  name: cluster-secrets
stringData:
  SECRET_DOMAIN: ENC[AES256_GCM,data:VitvzSpzhtYWkc8=,iv:R1NgbCbyHRb/htPmsuR5i6mNF9I/qyJNib2CsyE66/A=,tag:tRZ03SSgD0ACp2WHFOc6yQ==,type:str]
sops:
  age:
    - recipient: age1vec5q7tvefy794m00e59hfa7xj3twg9d8ecsk4khj36cduhfauasl45avn
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAwL1pLS3dqdUxJbXR3aFNy
        QlBDbUFLOWtwNkpQS2dkL3NicEtCMVVCWFRrCi9MaERGbFFFbi9qMnRnSVpxQmFL
        WU9iZnp3NGl1WCtITWp0L3FzZVlnWjAKLS0tIE03YSt6YTFtMWh0Tk5FVVQyRVpm
        LzNhVDYrWDV6SEVVQUJ5MW1RRVNEQk0KV47jQhpvlQy3B/W30LS9J3u19NIwst1k
        fyTOq4st0pONV7zstFeM+NRxI4Fq7sGbPTavQnyIAvN5syFXd9bZ2w==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-02-14T13:52:33Z"
  mac: ENC[AES256_GCM,data:SJICC6D1RWEI3lnTf9/x50j8emEfcDAT43XqFlX6Y58W0yQONg8Kf8yWUBs/ve2HMxDcg0dnyuG3znZIm77C3jtDzol4wq+BHS82s5KLIoGFzgGfM4hnwLPsz7FwRlye0mWpzwZkKesWuaTbMCSdQCbS38wrxkXNLdfwjDLxdkg=,iv:AncXHxxRxCtFHEdonlzgAv2Y427YHWFTF9qIcApjAqg=,tag:wVVuP7tzxMKxfmOIABGFsg==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
