apiVersion: v1
kind: Secret
metadata:
  name: cluster-secrets
stringData:
  SECRET_DOMAIN: ENC[AES256_GCM,data:JkA0PWKR99jH6IE=,iv:7EW5QXAM4jTENZQgtPr1aeJkmSeqKRek7cEN8EUNFSs=,tag:OxnL89aLLtsA56HFU7sRcw==,type:str]
sops:
  age:
    - recipient: age15krcjh9hpde6hxwrkwlkpksf0kxhjygryn52xahqkllj6d9724lsm0m33a
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBxaFpXUGFLZzVKazYydHB3
        KzRNaTcvS2Z1eXJEZkxVZ3E0eFJ0OFV5L3g0CmFWTFFsZ1drSmhsQ0JISTA4NG91
        RmtMMGZubXJpOVpxd0hpNTdDUUV2c0UKLS0tIE1wclYxZ1Y3Njc3SnNpd0xzKzFl
        WGdhUVJTRXAvUjZJbXBrck16VlVreEkKPFpchd8vFxgZ3/b2xEkE28l1SyNNS8NU
        coj43I2nKImTvKbUz5UuI98Y7aH7wFkudj1mmovgBxgaf0T0H47GLw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-02-15T06:22:14Z"
  mac: ENC[AES256_GCM,data:J2M4Vbs//JhupMPRRVCegLBcDNK1oHFD7Ze5+vQlkY4y/HXLVvsPACyhrs1hDPkDY3pEhz1CLT/25Ud1nGIK4pQv+2iiR8bjaFVcS2gA8Gixc5ELB5WONBC+9YqshRC1HzqlN5TskqnduxcOnKnQhfteRItabTpNA0q9tZAbrfU=,iv:zx1f6Eb4X2z5XW3NZ/Wlbi77g9xth6I+sJtKeWsaGOA=,tag:Rw+N8C/Rq+jHHy3WjbPlyw==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
