apiVersion: v1
kind: Secret
metadata:
  name: cluster-secrets
stringData:
  SECRET_DOMAIN: ENC[AES256_GCM,data:gT802jOjbcCVGkg=,iv:6nlpXqm7SKnHQSU8wR4+PoKQ+GWq/2nmVD1McLg+wVM=,tag:LAIc/36oEclllpLn0bwJwg==,type:str]
sops:
  age:
    - recipient: age14xzugqgv3lkrgvjpppls5vzn7j2vkrgxzghhkku7vpzf9cxjc3msdf4nha
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBQTlM1dEM2bUZDVDhGbUpI
        OFp0SlRFakR6TGRXYWpVWWdRSUhzam5FN1NJCjAzVDJNaXk0NHhhUXAvUTJMY2o2
        Qk5MS3R3cjcwVzJtZlVhb0EzQ3JYaFEKLS0tIHRnemVUZnlBbEl2Q2s3eTZKRm8v
        QVdzUi8xTE80WExOM1loaTdzNDhVOUUKDqGaMNGJTImwUewwBQ6G3LXsRmtQGK8T
        uzZ/YtynRHxyKolJP/P3rtP6u4zpWswc4voQXMTyF/rR39PQzBE6Jg==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-02-08T13:55:02Z"
  mac: ENC[AES256_GCM,data:eoueuN9g/HelXJngpDN/Kyxs+SVZuVxNQ1aAkXmzIoMR2sy16pWbGySc2cDlronMUJtfYZstnSfoy1/sljuWN8LvXwzFW0oZnnJFWPGVjj0XaIAe7CGPvqAeuzY1vlWDpV/vQZXAgwxF9c+lQQ48lkww7mUY/OcbIYcMkSVMOhM=,iv:jvrs0CbrKXemtaRJZ4YoJGNvx8z+VDBLmEB8FbMk3Ic=,tag:uxkYFGUZUpRUFbu/vhM5Ag==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
