apiVersion: v1
kind: Secret
metadata:
  name: cluster-secrets
stringData:
  SECRET_DOMAIN: ENC[AES256_GCM,data:gLlJ/Xneq4/V0WA=,iv:diPfT12HpqyWeFiLqrX9ecr02wpyeM6TfedJv0prNFE=,tag:/pPC/F0lkxCg8gT/HCWQeg==,type:str]
sops:
  age:
    - recipient: age14xzugqgv3lkrgvjpppls5vzn7j2vkrgxzghhkku7vpzf9cxjc3msdf4nha
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBXRmZwM05NL0xmRVhheVZP
        Q0JBZjFvMFkyci9abWZmb1NsR05jOGJsbjBvCmlZRDd0dkpPU3RDdU5vZ2I4dytU
        Q2JHVDBZVGtHRFZIUFFZM2ViWEZXa1EKLS0tIDBIcEh3NG1QenNsRUJXd1RTcTZh
        RkxnREx5WlFOaXJUWnBLWW5QeTZMRzAKxB6XFIsaJ3bULFTh+u+loU4D1x49LHqt
        vg+P6hmN+X4CorPXAQI92Q7IzCSc+S8ngJo/KokuPoBRM4a8y93seQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-02-14T00:53:38Z"
  mac: ENC[AES256_GCM,data:vQGng5dI4sDoPsel3DqaC1SS23V6CJIah/DcK3KRm93aabJ1mnCu1gD3immreMaFGpVHoxh83rA9kK+6bStwSotewYJwe+Cq/Kjv6E+Z87m6USnIpuCP92EqLVrdFhNITwgFWYQeKRV7m9BHVk+h2YX2wW0iMtuK2l9gVU3RWfk=,iv:2Difc6U0xXXu0TcLbhc7V+hfyz6zxWk47o8GZbIRrAo=,tag:Cy32jGPFhY/pblRtTA04lQ==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
