apiVersion: v1
kind: Secret
metadata:
  name: cluster-secrets
stringData:
  SECRET_DOMAIN: ENC[AES256_GCM,data:ArehkNFQ9NINRDs=,iv:rvS0p4GOhfoez1lzmaoPcbYw+N3YJK3zbkl+vu2wvtw=,tag:ndbPehB9YQS+vkj/a2FvoQ==,type:str]
sops:
  age:
    - recipient: age1zrsvwesl8thdppjq78dq5qyntpc959twe97mplqg393vwpvg0gpsd6wy4r
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBtcENPcWlTUWlFekdPTXFU
        dnk5VVYyTDQzNVhlOWpWN29ucEFKT1BzRmxVCldRRlFwOXJ2dFZoa3Y1TEhxMHB0
        QkJLWkl0T2licFM3TXJkbzUxRlM1VmsKLS0tIHJJeWVqc0E4UnpDRzUvNWtVcFU0
        aUdxd3FXVXhmdmN0RFF5UEh0TGhoM0EKVfll9i5Fp59RNBPIyD7rjcfSlymEmxQU
        Ts5tup2XvH4EqmNv6n7B2Q0DV+kumRBfbKfktfq9bnoOJr+whDHrGg==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-02-14T02:21:44Z"
  mac: ENC[AES256_GCM,data:CNq+19W7Dz6NaMw4R/9FkIKTXhnQyoOOVo3uWnsmwmeKnGzb6NkqGpsRtapEC3LcSkoBMgOBZqsXCYf/5/Xn3Npbiq2LJorskv9WPHEWOpBaMoRSo49F45LfnCwYYJscxtF2Jd6m0OHNs7MU03K3SWR41AAf9r2BVpyzu4whSuc=,iv:l8dPcvXySievVKZeBVE2ea4q29RIHiLUHD9qNEGMB1g=,tag:UynvnniIOQ9ZDYLqYS8vXw==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
