apiVersion: v1
kind: Secret
metadata:
  name: github-webhook-token-secret
stringData:
  token: ENC[AES256_GCM,data:bjvksyyUaZ0BoxChq43yJRqx27ml+TMysJZ19+QRwkw=,iv:8Ux/j3y/oWUT0Zz8p7WalIJsU4jnfVICSLXKh56op7M=,tag:ARBS3NpyMp5XPwNiUn0sAw==,type:str]
sops:
  age:
    - recipient: age14xzugqgv3lkrgvjpppls5vzn7j2vkrgxzghhkku7vpzf9cxjc3msdf4nha
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAxdUkrZGZYMlZrNkt0ZmJt
        MTJ6UkNNSVE0RGR5b3pIa2VvSm44eGxGSlhjCld5UTVNVi9lN25WeVMyT3Q0OUoy
        dGpFcDlDRE8yVEVlT0FBbDVQQlhVVFkKLS0tIG9XdTVEZXZjUEprWDl6MytnYXd0
        SWl2YTJrejdSbzBOSlU5TmkvSHlkOEkKBJexKQ+Y6DpRK75yI8HfHvPV0RCVG7JU
        SwwEMz+2UCrAW7SuDZsUqlheXdogNpfB84eZljJOqW8Sq2z9tiGzlQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-02-08T13:55:02Z"
  mac: ENC[AES256_GCM,data:UELbyuKTYKMvyY34CpzVa+tri4hDAZrxm2a1DGSXgg1dmeagdZTjrF+dxtEzYFvXycfg7yJfIS1WoiAVNETuHTbASms4MZ8oaubudXofb751sWLfb+gHTuBuX5EB0BX1ni4+0xW+r8LDDfgV22dvhilsJaQKMNdgW3qTXlwrOmU=,iv:ZHWbPNzCdLGml5g78i2/BcHD1RF+5SmaDGyNViGBcf8=,tag:fkqazg7UyniL9ohDwDsqwA==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
