apiVersion: v1
kind: Secret
metadata:
  name: github-webhook-token-secret
stringData:
  token: ENC[AES256_GCM,data:wvseyar8D9FDfYdrSc3I45PyitEvSqQVj90z26qX9PY=,iv:rDNfFwCl2nttzfJu3sxDEW0oHOyhOCNS0V/XowNDIyw=,tag:ltRwuIW0ZjQeJqBf9SfK+A==,type:str]
sops:
  age:
    - recipient: age15krcjh9hpde6hxwrkwlkpksf0kxhjygryn52xahqkllj6d9724lsm0m33a
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBhTHlZa3FyZ3JIWGxzNSt5
        Tys3Q3ZoM3FPS0NjUTBjbktTVHcyNCtzVmxZClQ2aEg5M1NpUkxzMENUZmhZSWFG
        Z1lrL1R1bDZpOWJRSjNPazYrNEdCVEEKLS0tIC9CZldNVUlhTm1VSW00NFVGbUhE
        aWd6L1ZTWGpUQlpLbnJzQm1FZDVqejAKCIPumBQ1rjQE/+N6HHSbznOaMelb3bz/
        HvU60H1a00AqL8CyeQiRifRIrrxDf/YyDmTkds7UWj7cDplN9diWMg==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-02-15T06:22:14Z"
  mac: ENC[AES256_GCM,data:dwvOR+8fvmExCoR1kIWBvhtTz14yXnsfgtqrV9+Jvvj8fnAaaImWDLl+oGy6wK+ANw9ALjk4X2v6+YT8v8c9Zx8uWmzLm6B+PjdT+tlCS0FUrU2zZ52cwjVe78qMcURRUEIWmCcVT+Y6ScXAXUqe8Fg0xz57AnLVSjnLyvQuNVE=,iv:5FgHseoSzaielAJRiexV/3k/gsZGZchCsj0FLR6oxew=,tag:eS1JHkM6ZKy1LvtvRYqQJA==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
