apiVersion: v1
kind: Secret
metadata:
  name: github-webhook-token-secret
stringData:
  token: ENC[AES256_GCM,data:iQdf3JIRIEJ6FE1E6IX2wbbqCshRQ0prL/3fsC0HOsA=,iv:kMrJ25+yTNCaVr+Om+9pDxVoMPWJuaf5+F5cbpnXjt8=,tag:lsNuak9f+e83emob2dngvw==,type:str]
sops:
  age:
    - recipient: age1vec5q7tvefy794m00e59hfa7xj3twg9d8ecsk4khj36cduhfauasl45avn
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB6bXBkYUFlSkUyVWMxM2VC
        WFVISjlZV1pQYlJGMDc2UGVuemRvM1VnbXlJCmxaaldQSUlUeFZNY0R3Y294S2Vw
        TDI1TUNQUUpoMjJ3MUtqb01md1hJY1kKLS0tIG8vSDdKYW1BYmxwSEtkQTcvNE1u
        c3hWMTc5dldDZWlGU3hrNGcybERBQXcKRe/FVlfN/zcXLd0w3GH4lsDQio6Ju1Hx
        wG2ZODJTC9GWAkNIkMkMmcGzh+u7HApc/7ceS0oKhRRIaJfK+tayzw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-02-14T13:52:33Z"
  mac: ENC[AES256_GCM,data:unjIQnRwEJv2Fgv+nzd/ZXFZdPP7POICJ3DAso0QiUcYwFFecziIlYXSxSzxQZbvnM7rJLYZyyYGxBVyaaqoY3h9SGzaKhcyE+AgbSPseeNujsjFG43wUwfP/UtFjmGXzThDrXFMN0oM3YfTJZ7oP1+eojlQtRboYQxV3OAwNuQ=,iv:PZvO1WpGTuETfDgfUsAAbqTGvMvuMwEgcd4We7aqUF4=,tag:YZ7h1j/YZuVyoPbjJYEkcA==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
