apiVersion: v1
kind: Secret
metadata:
  name: github-webhook-token-secret
stringData:
  token: ENC[AES256_GCM,data:eHNoPQRhO2ES3gpKL+u5ulwv1rtyOHip+/mZPlFEHyI=,iv:+Hb5r5kzEfROT+W3/ISM1Y7ZjttQxNsRPwmPI3exQQ0=,tag:4ff1sTnkfwhPiUUfn+2/5Q==,type:str]
sops:
  age:
    - recipient: age1zrsvwesl8thdppjq78dq5qyntpc959twe97mplqg393vwpvg0gpsd6wy4r
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB2V0lESWdvM0MrQTdVb1RX
        TEcxRUg2VHJDMmoydnVjU2FSNkZObEIwWGxVCjlyOTRDSzBsc2lnd2cvWks4c2Rk
        MSt1TjJLZWtXaEVsb3ltRFFhL0F3Sk0KLS0tIEdTZVRZam42VjRKMzB1Y1BCYnV4
        TEFYbFVaUG1ZeTlBZG9FY2tXTDNrZ2sKr6ma5HwFYiGrbWLoSWOEuIfIQJDT+CWB
        7b2BR0XXozEBOXEq3/wyETl/LNdFTMr+X0hJBmRyI6SNoAaBThVzGA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-02-14T02:21:44Z"
  mac: ENC[AES256_GCM,data:dNHxcG3MKXUXcXIOxboDy3BKqeqKGUHI4sEn4vl3v7lfpFrdkmgYzGYUciLdp21fceUeo4jaa1dLVdUka8KnEb1rmvEqIftJHfLbnGQCdGx4KEzWDumjUdTuPvBGiVxz4mYzZHwxTaiNT5qwAb5wasdHlRAuzBZ3VI+xXEZsrtk=,iv:Rb6iE91bSjdtrFEo3fI3S5ldHjPVxHXcAJv00f5XaY8=,tag:XSUdj0d43ei2kBYU8SlJgQ==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
