apiVersion: v1
kind: Secret
metadata:
  name: github-webhook-token-secret
stringData:
  token: ENC[AES256_GCM,data:ALNgWfGy6cF0eDQJGjWPG7129CISgxNrl899Ie3wlY8=,iv:x0KudlAVkVLjduMq6R13+OKdVk1EoVqDBlovTul309Q=,tag:rCF7g8NaV88O5e3Eby+hzg==,type:str]
sops:
  age:
    - recipient: age14xzugqgv3lkrgvjpppls5vzn7j2vkrgxzghhkku7vpzf9cxjc3msdf4nha
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBzTDdQTCtIV3Z6MnZZcUFK
        emxrMnBTTmtScXlVS1ZzTFlnWjBZUUhuZGdJCnJWQnRadDlwSjZXRWVRMzczMysw
        djRQUlhNVjBiVktlVEo3Zm9EZG9SQmcKLS0tIGxXOEFOS05xOStpVDFjMUtPbzdQ
        WExCczdQUXh6SnlWSmJjUjFRT2QyUDgKjA9oZtjf4R6HKpxQVdKwASU8E2MWzpv2
        psGeUFWS9Cn2/6kiANk+KJN1nlUiFM5H94ckVLD4gAFTX6nKNoYbbQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-02-14T00:53:38Z"
  mac: ENC[AES256_GCM,data:YIcIusDy9D7dQQTA785zMRyguPaQ8QtkmexPSrWCfhVZKFCehViMinl34sPTj7ih2Z77cUZnDMXihP6+G4DU3srl1EvJg1z6Mu2bfAvBcL/ywp0Y8olb0w2UGj3dIPIbwzGprVMf4Tk+NB1tD4NtmNwENYZRXKsWPHiGudE2BRE=,iv:Dfu26zPown1ZZeq8NZ+lHM2bbumdS17e+uR2hjR09Jo=,tag://Lwuz/oc7fKxyAGI6ZKGg==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
