apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-tunnel-secret
stringData:
  TUNNEL_TOKEN: ENC[AES256_GCM,data:gwd/Qgu6HZ8gTJKZRCBmw3Q3IGz4sNPCL59bMNWDy6dOtXdqgDDNI4soC6UAfABQunpAelt0CGY33MsKUDubL+NCO6IbCE/9o+9itejZBcwQOOWirYN829Cjgcv35yRKjO3xDo2bM4IVP3Bq0j6LS2OtBhEhchhEuKbynLDp6IZeAVMyv6wBJPm5Q5NXBDqt8Z2aC/qYX4HsiwKGlPNCn2utPiyg4k/tLSl14PReDpLX5yv5,iv:TsrYUEJfEIGJUTkJ9BgRA0w9MLciESiOz2izvhOyGvk=,tag:TjQYtyqWxrU2K5K+xb0mGw==,type:str]
sops:
  age:
    - recipient: age14xzugqgv3lkrgvjpppls5vzn7j2vkrgxzghhkku7vpzf9cxjc3msdf4nha
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBCNHVnYXpiV29mRm82S1Ez
        QU8rOWNOSm5RTTc1eEZBc0NIenhsVXp3WmprCkg0QXpTL243RnkzNjFucUlsVUQ2
        a1l6cS94clg1QnpvSkxBNnY4ZjlRd2sKLS0tIExDT3RMQ3k3SXA3SzdDcDNuSytF
        ME5oN1g1a091Rzd4eXExd0FMMnd2eTQKoijQCwsH1Xfl4k5npyK/L/KMvs7DZUu7
        cc8X4LdUJwdnUwczA6ALIrvBV5s9Qi8OWgVOIPPClIEwWzzX2C92RA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-02-14T00:53:39Z"
  mac: ENC[AES256_GCM,data:Ju0bOOKhLpaq8eh6Z0tTBH0aNSqVAjPDJxn9NKO/9Aor6gRadggj2+5pZu9aIJyeirMaKleGT5YEYi9WL21l/J7CyKxas8BtKn0HApp3Ximz1d5LOQhOx19Es0Qof6+yUYnpF9jLdDluYp8dd/d2tac9WP5OdtxtQGjRrM4CPG0=,iv:VZ7G6i84DvpAqLSMcutYy9s85hLSFTB0HwRiD+3rmFI=,tag:AU2Fct6yYiOtXcUKVk49Iw==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
