apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-tunnel-secret
stringData:
  TUNNEL_TOKEN: ENC[AES256_GCM,data:cMzqnqFyhg/JOu5pKtG2cteXd8oHfp5+mouj2lFvwWAxuZ4232WUTLt0wHkdE9TPOMcPOHHhMX2NOYa/AuAnp6xfyplczV9Ci8hc+Ri89pu4m0HhePxJgBmu/6vyIQUPrxLxUKnk/SWeVv4dI/W1XTlBDqJZRSNrX0lKDo/pcEq11TNH5YVhYtUcGBktO64AeMOnNh9FgdygLP+KLauY26A30Wr8ker7i0LoTeN8WdETE0T7,iv:jJw7PdxNZC7flwbnPrxKrRiRMjm0DDvjVyjUu0FIF+w=,tag:4uhhmO7jJjVQ/KM6olflrg==,type:str]
sops:
  age:
    - recipient: age1vec5q7tvefy794m00e59hfa7xj3twg9d8ecsk4khj36cduhfauasl45avn
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBVczNqOVVvZkY3ZjhabzFW
        RHZBYkJraUVKUXZsY2FaUElPWFZrWURxT2xRCjE3Sm5TcUp2cjZ3eDF0bXRFa3ls
        N3FSNEw2ZXpWUmx1MnF4c0FIK2xFNUkKLS0tICt6ZncwU3JlRlkvQzhDdHdrRUZE
        SE9kSTgvRURZZEkyQzhkM3Z4SlRtc0EKKyFV+GI6AevI8EJXCte0CZLXG2wztjew
        xFO9c6SwL1LugJuT+nhzwJ5XzuTY1QdSUKvB3a7fsLOVDkxknNi1Yg==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-02-14T13:52:34Z"
  mac: ENC[AES256_GCM,data:2r8soLThIiqMmGuFXNIVEiMMW+8QYAPnk0I0ikYTq7HpzxI2hV/fxybpUgzzRBgoA8lGzCmvPDQbzCRoqvQ7XPHgsf7WkIxipOzYLHGVD/+YYrsV1HRRdWkTH9A+JZPKH5wZwHJi2NbyNszwV/etVNa7IxOGDktGwOw0CvELmbU=,iv:mNLBfo6E2A/XLLmdsPWGCucJ7a24CnkJKq8Wr7fGNBI=,tag:mH+yYo8kQ33nA8q1gprplw==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
