apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-tunnel-secret
stringData:
  TUNNEL_TOKEN: ENC[AES256_GCM,data:GICD9A8+r0SIUqDUpd9r6JzCtiyNaIM4MuKcLwUBKlMNVvTp3vwTdo9rnqLV0Ey9rrtvsKINusOm5nNAUIzy8pY8Nyxc4NWVMkqT3UA9KGGdZd1zGijhLbg5pIQmhNt+NOA0jRZo6dYNcSVGd7NbVa6bQZeRVTJ2TTkTkTsIj6ZPVQ1ZHAgUtzi6QlMeNO/XSA/0FrV7dYgtdZsp1jRVxigG6D9EpO7vSNQdWBMskbI05gXR,iv:gwiKRT3UJP6AkIUM4twiMgF4rpYMPgdXql+8Cg+L8/M=,tag:kY8ZsnpBjAhnyyHsRZ/wYQ==,type:str]
sops:
  age:
    - recipient: age14xzugqgv3lkrgvjpppls5vzn7j2vkrgxzghhkku7vpzf9cxjc3msdf4nha
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBvQVBQVTkxWE50RHdLQTZS
        R1VVRC9IcnBSVGpCak5ON1lJalNEaG54WURzCmJnMllNaC9CZUdqREtrYlZIQ3Nm
        dmIvaWdvdVlTOWJJaDl2MjJWYUMxZXcKLS0tIDltbmNjU09WSEczOGJIanNna2Vm
        TW1iZUlXcFlLRjBVZWk3cUdtZkdJbVEK3fLb4ZOAt8wcYckiqevzVCFWkKA3arf5
        MD83Pn7eIA5nmJo4MLzxQrdNJ+XqZU+6ZkPbkl5cx7hZl1A5XZ81Bw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-02-08T13:55:02Z"
  mac: ENC[AES256_GCM,data:rvnZoGuLLAw9/hFS+WJshVZ7BgthEgu4qzUEhDOcItSSTVBMCCyGh4TaBca9YyjiIw4/NtsS/QoTJ2Kiauyq5UwkyvefLZYwFILGMGhx8OwUWXByF29XAdOAvNfq4lTMNHIq9AnObNal/HaCgEiuHoFDK69jeGWw/0eNHj1B7zE=,iv:WGYkge+6kdANYE4DnScGDlXAVLpi1a7biZhXdtC1xgo=,tag:bT1w5nAfNDuk12owaO2h5g==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
