apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-tunnel-secret
stringData:
  TUNNEL_TOKEN: ENC[AES256_GCM,data:GPv18bd9L8ocbNUyGNkINuAMLTr+6jFB7vSWIkvpQzvw24I2xVcLB24SZmPFD9QU9dXaV/Eq3F5x7cZjiSi3tlBihRAgtW9N/U/16lzO5Ud4uZa/+zWPT/q5C6+5BKDLIHOdFc8OISyp1sylFs8g0Rqeo1o7xWAAMq1eAcMQBnv2X9S/GEC5yqT/ZBUe+3Rp9++Sk63I/Tu1uinRvNT+/VTFn2wqLo7fvh93Yc2BwBBaU0Hh,iv:r5+jbla7Exvw5cjzggnMVx/jnnN2BhHe1iD+LrpsjM4=,tag:7GT3BvWARgNRut19E4CAzw==,type:str]
sops:
  age:
    - recipient: age15krcjh9hpde6hxwrkwlkpksf0kxhjygryn52xahqkllj6d9724lsm0m33a
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAvWkFMeDNUMmdXL0x1aVQy
        ZzFzSkV2QUJMeUxYMC9RRVBVNExwTHY4STBRCm9nRUpVUm9xQ2xVVHFlNDJib3Jo
        Nml3VTJCOFZHWWVNVDFBcFN0UFhlK0EKLS0tIGVxejBVdGFiK3lTODZaQVN3TE5D
        djhmNGswb0szWm03cG00UWhGdjJsWVEK6IljB1k988ydkEQfyxMe1r4C2QMrx4o3
        NHumSrm4/ua2pRG26P2AkjQNJsTtUigzUlaVHvTaE5Ge7DEecAg23Q==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-02-15T06:22:14Z"
  mac: ENC[AES256_GCM,data:7bEidyEHGPH5Lg0c7pNkfQ/wC+bbjieGydUp3H/MkpmYOP9Mq84kvk5N944cf9o7Nz0SV3P9NfIKfOBeGQAmvdHBPBpLdm3DgxtdzfcbnDcX4JRL6yC3nkOnwWHaCIUdfKdYcP3VhUazCeW+ZQFy4g9CEuWG6L8rcv8P3ejZ2Ac=,iv:Sbe/+PxCPPq9jqPnEUL7cO5jCP2WQpEsDuv0uZpwOKE=,tag:Zkj9wQigOFkJ4DrS92qtAg==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
