apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-tunnel-secret
stringData:
  TUNNEL_TOKEN: ENC[AES256_GCM,data:0aNBabOjBtlwIVbnVCs1xEMdTmxiaq6KSLx3HfYaIs8d17eq0GohoazaAlJ4NKnEM2U0DMOsBVQXathKpDA1SWWZYzGcyIhFCoxBR4lUVvFQRny3lb/IRyUqfkvGTDdC8Zg+rWsNyrnR371aCMGRe6ZsusLdrxoUgqq6Rn+q0uD06F6RLo0/M4j38Vv6w6XsGlTC++S30XBQLOeU9VPA9TkAiRVSIbSJYW74UwEhiMNhqHTK,iv:LOgO3iLxWaxZkK1urUt3nqjLOiFvKnLrzDTIUKqIzZE=,tag:9NzyJ/AYpFkfnKi0Ez3vCw==,type:str]
sops:
  age:
    - recipient: age1zrsvwesl8thdppjq78dq5qyntpc959twe97mplqg393vwpvg0gpsd6wy4r
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBWR01xbTMxMUd5MHJLb0JM
        WjdQeWcvSk1zWkphMVM4eVBrRUwwSEZLQWdrCmQwQk41MUhZU2Z4eVlXN1JzSlh4
        cDRvaWtQOVIwVU9QdllVa2UrcTVWTTQKLS0tIEVqRDFDMnNPNXBUUDBKS1V6eE11
        ZHd5b2UrazJoYndURkVqKzByL0RUVW8KQu84pCDce+vTfPMwdTLVH1476Cn4l8mw
        vd5J7FWU72wiF32wIawJXYYkbXvYNfGd7vprzFAwLaX0mRtTGptz+w==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-02-14T02:21:45Z"
  mac: ENC[AES256_GCM,data:z+rVQlpKaQb1yKAY31zQPzCNHetK+1JLrOIf0jV5A+e8nHQGOhCu/M77bJmm+cmcaldkhT3KPTG3Kl812KctOd8nsF7BfxTnp5E66K7CfiKvBvQITIgQag7nVfrYJ9+/ZAymx7QeYpflWUqtOOJskDECQi+574Ajjfd3Q9h2ppQ=,iv:9ddu7vB03AOD7Af5wmqdJ8DccdI0fPh+GxocMD1DvXA=,tag:qqPUrSlR/RLCwG9XueCXPA==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
