apiVersion: v1
kind: Secret
metadata:
  name: cert-manager-secret
stringData:
  api-token: ENC[AES256_GCM,data:7T1aRhHGRlVjoXIjIC6orLl7IWzARQUt66VsGrAMzcGu/mTYe7Ikiw==,iv:cHglNY+laGwmi5Wb2E/0A8ECBBr4e3yEap2IION3CZY=,tag:crtb+082FpDs9Ygv/Ir1tw==,type:str]
sops:
  age:
    - recipient: age1vec5q7tvefy794m00e59hfa7xj3twg9d8ecsk4khj36cduhfauasl45avn
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBrRVRjTUI2QzMxN0lmaWZJ
        alBrbEZpczJNTHF1T2xFRDdoMUs5RWtWRGxvCmVtTlBjcHFpS1UwdnBreDQ2YURa
        WGl5RCtHeGR4cHFHRFVKamlzd0pBckkKLS0tIHN3NUx1TmJYZ09UdzJzNkVONTda
        K3JkU3FmOUJXZW1CODRTOUZ6anVVbXcKIKC84833Wum7hlLkLWT2IJkMqyxTX52b
        DCohTRRKrcs5N8lK4guX2UKcJXvsJJ7woU6eUuChAu2ECTUMCesojA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-02-14T13:52:33Z"
  mac: ENC[AES256_GCM,data:MWEFR6NDlY4rqMBj/MbfWdM9CauHxrH4/70CKgfFmaqHwZr/rtiSZBF0VS5EL2h2SJ1gwE8UVwp8wG4RgcAQQMl4QXZQekKcZlH1abNpN51zN21inSnRSPWoWjRyFKMOl30M8WADGAJkXQevdseHkE0e5Z4FsbigreW1P5BfE8U=,iv:0AOWsml+OoOcJ/CaDV2ESTA0rJqWmjjH0gudBYJscr0=,tag:1Q4HsGFRjFtFJG0BNP1Gdw==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
