apiVersion: v1
kind: Secret
metadata:
  name: cert-manager-secret
stringData:
  api-token: ENC[AES256_GCM,data:b4DNP+1BK6HuZ/ZcGdWU+wx1Z7YLgrDGNDGb3jxN2V+WT0QeZ3sOoA==,iv:4gWVcYGMu5W/MhVbMDw03q1Nic1+CtcPnArY8U0yDY4=,tag:wtKZyRWA371ILV5f+a/18g==,type:str]
sops:
  age:
    - recipient: age15krcjh9hpde6hxwrkwlkpksf0kxhjygryn52xahqkllj6d9724lsm0m33a
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBwb1pJbTNyaGRWdWRnVmFE
        UWxjdUN4NlRMelc1TGs5M0RRVVlkKzhVTGxFCm4wbTNJdVIrYkJCQlpwNkV1ZzZm
        cjM3bWlOMnNUdlh2bWlTWUtCRTNvd0EKLS0tIGZJNzdNVFVZRmtxSk5mTW1qcElG
        TzVOVGJVbXNGc0svTERtUS9xemhYVGcKznpx8URnndyxeDuGhtATOBZUQx8JPZ9e
        HsV+xOPu4YkdfUysF3/Be+ye//kt3YYf9+DKyVgnpfk/TEcDrmoVCQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-02-15T06:22:14Z"
  mac: ENC[AES256_GCM,data:icnDlyAYJ84M8Twh5plZM8Yvy4UzauheY+VsOOFxG8juEg7hvG9y8gPhD+q/CzKk4d2QLLGmaEn6a4QzYEIA2LP5sTL/Ji1hiIap7BDnfEKY7vEcfdEtDdrGRfeDSDvQ59RcQv2/yQdJuTgtZVJf5+j/bFC9QK1ahxfDaO7E/DU=,iv:i3wLgOtLYIErLCu/ZZeUZxtQMW5TK4HU/DMAWYdsrEU=,tag:WSGoTPoOUMoCvQ1rOoH5NQ==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
