apiVersion: v1
kind: Secret
metadata:
  name: cert-manager-secret
stringData:
  api-token: ENC[AES256_GCM,data:Sl5CgCKgIsdG3TJmz0vmqHSOTueOFm+LKxirkPQXVg+QUsA6c42Wdw==,iv:G3Es8+t3UVuscUGjMMF+QlGREahLuIFqPGHz8+zWHEA=,tag:LNAw+syZe684QlRj5xtvnA==,type:str]
sops:
  age:
    - recipient: age14xzugqgv3lkrgvjpppls5vzn7j2vkrgxzghhkku7vpzf9cxjc3msdf4nha
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA0bE9vL1dYVnNwMlhycE5k
        aTg5ei9CTmxoaXAzSnlxTkhHM1ZXYUFPUUdFCk12RnhkSDRZK3VwWU5BN1RqRjND
        S3BTbG9udE4vcVY1azFHbWw2cHZFRWMKLS0tIFM1OUZXRFZkVzFOQzgxdXlabm1O
        eFRqY1RHT3lvMVg5cUFVMkVPdG1WZG8KzaWmS6/tgoLhVJwIhVHlPKs/IWAb4ly9
        gELwFHGHdhNYYLrz3nud17JKlYelooFzcCUzIy2duuTyLeRTIGBv1Q==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-02-08T13:55:02Z"
  mac: ENC[AES256_GCM,data:xmVV4AD2FUebkw/T5Etc4oBdQnJofEfUuD7TP4jv5Dm2Ood4jDfHjGHERdMAap9hZ0+LqTDnNSQ/KZRTAfJQXgrYsAVfeb2wbjucHXDhncVjyPq2kV7eGItQqbVrE26zu2VCK5gpNdyvJO2m63jBNJeoEbPOAUIUJYGQ4ufBEvM=,iv:3w7NLakrG5TZ1ICjUPUezBPJMutKszBmiYzyCOWJbys=,tag:Qu8aafsAXd+P27UbZnv0Gw==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
