apiVersion: v1
kind: Secret
metadata:
  name: cert-manager-secret
stringData:
  api-token: ENC[AES256_GCM,data:4DV/Vzah1/cKEwRemFsJZ/mj7oLg0NQZSVluPjXyZXhbpH8VMJhiXg==,iv:2Q40ug7aha/JeiMtfBS14MIl7dhqZOoF0FnKHv+al1o=,tag:Xy80TqcUfwHWmcks219RvQ==,type:str]
sops:
  age:
    - recipient: age14xzugqgv3lkrgvjpppls5vzn7j2vkrgxzghhkku7vpzf9cxjc3msdf4nha
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBEN3A3RDM5dkh1VHZMdmFk
        NDNlZjQ1cjU5REdkR0g4MC9Db1IwN2xMRkE4CjA4M1AxS1BLUThtL2lKVDgzdzk2
        cVB3RVRlb0RIUGNDOEk5K05GQkJFaUUKLS0tIDh0TDdVZktzb2hVRjd4ZUs2OTZN
        bnIwc0ZrRXZOZ0JHSnJheU5qMEdFbTAKb9/bLHDOAizCKX3SREqforrqdHMjRbsM
        DU++B08+AGkfAGW2pmE+rsx0qDbje8rGYfL+GGgi8Gfeaxu4mf8PnA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-02-14T00:53:38Z"
  mac: ENC[AES256_GCM,data:K/PYUCZXBAc3Ulm2Ys3IsJFo1kFppRQAcc/b4rGbX773fBSaMhto0veKY40fmfo1Cq9jMGRtsB3oCc3e/SR9DnGMKlDQvJJKgT4xs6rTzCzjB640aewCRSQA1B3fG5RH5OF4WBeHa2AxVXjEKOeX0/Y4FHxY1NmthaYFMwUj9a4=,iv:Mt5CROUhi02UYRD7+lPfG8PCzyd6NILnUdnT0zY8/2U=,tag:+ZN6F5WfuaaE9Aoy07lUDA==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
